

data:
  # train_files: hiyouga/math12k@train
  # val_files: hiyouga/math12k@test
  prompt_key: problem
  answer_key: answer
  image_key: images
  video_key: videos
  image_dir: null
  video_fps: 2.0
  max_prompt_length: 8192
  max_response_length: 2048
  min_pixels: 200704
  # max_pixels: 786432
  max_pixels: 401408
  rollout_batch_size: 64  # equivalent to verl's data.train_batch_size 
  mini_rollout_batch_size: null  # equivalent to verl's data.gen_batch_size
  val_batch_size: 128
  format_prompt: ./examples/format_prompt/toolsrl.jinja
  override_chat_template: null
  shuffle: true
  seed: 1
  filter_overlong_prompts: false

algorithm:
  adv_estimator: grpo
  disable_kl: true
  use_kl_loss: false
  kl_penalty: low_var_kl
  kl_coef: 1.0e-2
  online_filtering: true  # dapo filter groups
  filter_key: overall
  filter_low: 0.1
  filter_high: 0.9

worker:
  actor:
    global_batch_size:  32  # equivalent to verl's actor.ppo_mini_batch_size
    micro_batch_size_per_device_for_update: 1  # equivalent to verl's actor.ppo_micro_batch_size_per_gpu
    micro_batch_size_per_device_for_experience: 2  # equivalent to verl's rollout.log_prob_micro_batch_size_per_gpu
    max_grad_norm: 1.0
    padding_free: true
    dynamic_batching: true
    ulysses_size: 1
    clip_ratio_low: 0.2
    clip_ratio_high: 0.28
    clip_ratio_dual: 10.0
    model:
      model_path: Qwen/Qwen2.5-7B-Instruct
      enable_gradient_checkpointing: true
      trust_remote_code: false
      freeze_vision_tower: true
    optim:
      lr: 1.0e-6
      weight_decay: 1.0e-2
      strategy: adamw  # {adamw, adamw_bf16}
      lr_warmup_ratio: 0.0
    fsdp:
      enable_full_shard: true
      enable_cpu_offload: false
      enable_rank0_init: true
    offload:
      offload_params: true  # true: more CPU memory; false: more GPU memory
      offload_optimizer: true  # true: more CPU memory; false: more GPU memory
  rollout:
    n: 8
    temperature: 1.0
    top_p: 1.0
    limit_images: 0
    gpu_memory_utilization: 0.6
    max_num_batched_tokens: 20000
    enforce_eager: false
    enable_chunked_prefill: false
    tensor_parallel_size: 2
    disable_tqdm: false
    val_override_config:
      temperature: 0.6
      top_p: 0.95
      n: 1

  ref:
    fsdp:
      enable_full_shard: true
      enable_cpu_offload: true  # true: more CPU memory; false: more GPU memory
      enable_rank0_init: true
    offload:
      offload_params: false

  reward:
    reward_function: Lang2Act/src/Easyr1/examples/reward_function/toolrl.py:compute_score

trainer:
  # total_epochs: 10
  total_epochs: 3
  max_steps: null
  project_name: Lang2Act
  experiment_name: qwen2_5_7b_toolsrl
  logger: ["console", "wanlab"]
  nnodes: 1
  n_gpus_per_node: 4
  val_freq: 40
  val_before_train: false
  val_only: false
  val_generations_to_log: 3
  save_freq: 40
  save_limit: 2
  save_model_only: false
  save_checkpoint_path: null
  load_checkpoint_path: null
